export const TAX_RATE = 0.075; // 7.5% 
export const MENU = [
  {
    id: 1,
    name: "Kung Pao Brussels",
    description: "Almond Chimichurri, Gochujang Mayo, Crunchy Garlic",
    price: 8,
    category: "For Sharing",
  },
  {
    id: 2,
    name: "Crispy Deviled Eggs",
    description: "Crispy Whites, Miso Mayo, Chili Crisp",
    price: 8,
    category: "For Sharing",
  },
  {
    id: 3,
    name: "Kimchi Grilled Cheese",
    description: "Local Kimchi, Mozzarella, Gochujang Mayo, on Fresh Sourdough.",
    price: 14,
    category: "Handhelds",
  },
  {
    id: 4,
    name: "Nashville Chicken Sliders",
    description: "Crispy Chicken Thigh, Nashville Sauce, Kimchi Ranch, Quickles, on Fresh Japanese Milkbread.",
    price: 15,
    category: "Handhelds",
  },
  {
    id: 5,
    name: "Pastrami",
    description: "House Cured Pastrami, Thin Sliced, House Kraut, 1000 Island, Aged White Cheddar, On Fresh Sourdough.",
    price: 16,
    category: "Handhelds",
  },
  {
    id: 6,
    name: "Collard Green Melt",
    description: "House Collards, Fontina & Mozzarella, Chili Crisp Mayo, Yuzu Coleslaw, on Fresh Sourdouch Bread",
    price: 16,
    category: "Handhelds",
  },
  {
    id: 7,
    name: "Crispy Redfish",
    description: "Pan Fried Redfish, Korean Tartar, Aged White Cheddar, on Fresh Japanese Milkbread Sesame Bun",
    price: 16,
    category: "Handhelds",
  },
  {
    id: 8,
    name: "Kung Pao Brussels Sprouts",
    description: "Almond Chimichurri, Gochujang Mayo, Crunchy Garlic",
    price: 4,
    category: "Sides",
  },
  {
    id: 9,
    name: "Naked Kitchen Fries",
    description: "Lightly Fermented, Miso Mayo, Fresh Ketchup",
    price: 4,
    category: "Sides",
  },
  {
    id: 10,
    name: "Yuzu Slaw",
    description: "Cabbage, Carrots, Shallots, Yuzu Vinaigrette",
    price: 4,
    category: "Sides",
  },
   {
    id: 11,
    name: "Collard Greens",
    description: "Coconut Milk Broth, Crunchy Garlic",
    price: 5,
    category: "Sides",
  },
   {
    id: 12,
    name: "Sesame Pesto Pasta",
    description: "Local Basil, Fresh Spaghetti, Cotija Cheese, Crunchy Garlic",
    price: 5,
    category: "Sides",
  },
  {
    id: 13,
    name: "Fried Rice",
    description: "Bacon, Egg, Green onion, Gochujang Mayo",
    price: 5,
    category: "Sides",
  },
  {
    id: 14,
    name: "Beef Rendang Bowl",
    description: "Indonesian Braised Chuck, Jasmine Rice, Pickled Fresno Peppers, Braised Collards",
    price: 16,
    category: "Bowls",
  },
   {
    id: 15,
    name: "Redfish Bowl",
    description: "Blackened Redfish, Gochujang Risotto, Yuzu and Herb Cream Sauce, Local Micro Green Salad",
    price: 17,
    category: "Bowls",
  },
   {
    id: 16,
    name: "Plant Bowl",
    description: "Protein Greens, Black Lentils, Rice, Kung Pao Brussels, Cherry Tomato, Pickled Shallots, Fermented Cucumbers, Almond Chimichurri, Avocado, Garlic Crunch, Fried Egg, Green Yuzu Kosho Sauce",
    price: 14,
    category: "Bowls",
  },
   {
    id: 17,
    name: "Crispy Chicken Caessar",
    description: "Crispy Chicken Tenders, Local Romaine, Parmesean, Milk Bread Croutons, Sesame Seed",
    price: 15,
    category: "Bowls",
  },
   {
    id: 18,
    name: "Yuzu Cream Pie",
    description: "Riff on a Key Lime Pie sub Yuzu. Served with Whipped Cream",
    price: 5,
    category: "Dessert",
  },
  {
    id: 19,
    name: "Thai Tea Tres Leches",
    description: "Served with whipped cream",
    price: 5,
    category: "Dessert",
  },
    {
    id: 20,
    name: "Whole Roasted Chicken",
    description: "Lemongrass & Cilantro Rub, Honey Basted, Side of Basting Jus",
    price: 46,
    category: "Main",
  },
    {
    id: 21,
    name: "Slow Roasted Pork Shoulder",
    description: "Korean BBQ Glaze, Side of BBQ Sauce",
    price: 50,
    category: "Main",
  },
];

